### ISSUE TITLE
Question Regarding Compatibility with Other ESP32 Hardware

### ISSUE THREAD

**Issue by MoonKnight171** [mrslycat/crsf-link-tester#1]
Hello,

I hope you are doing well. I am currently trying to use your project with an ESP32 WROOM board and a TFT display that utilizes the ILI9341 driver. I was able to get the screen working with some basic examples in the Arduino IDE, but when I upload your code via Visual Studio Code, the screen remains white.

Could you please guide me on how to resolve this issue? Any insights or recommendations would be greatly appreciated.

Thank you for your help!

Best regards,
MoonKnight171

**Comment by Den41k92** [comment]
Greetings MoonKnight171,

I looked into the issue and realized that the code I wrote is too much dependant on M5 hardware.
Most of LCD initialization stuff is already done in M5Core2 library code, the reason you see a white screen is probably because you compile for M5core2 hardware (using a library) but your setup has different pins for display connection.

I've just made some changes in the latest commit and manually initialized TFT_eSPI library using an another dev board that I have: it's "ESP32 2432S028" which also has ILI9341 based display.

Try the following:
1. Pull the latest commit
2. In vscode, change the environment to `env:esp32_custom_ili9341`
3. Edit the display pinout under the `[env:esp32_custom_ili9341]` section in `platformio.ini` file if you need to; also take a look on `PIN_RX`, thats a pin connected to TX of the receiver
4. Compile and upload

I did a quick test and the display seems to work with my dev board, at least now it shows "RX WAIT"
Unfortunately, I didn't have enough time to wire and test it with an actual rx module. Let me know if it works for you, otherwise I'll try to test it tomorrow.

**Comment by MoonKnight171** [comment]
I tried it and it works! I really appreciate your quick response and the help you provided. It made a big difference.  I’d love to see more projects like this from you in the future. Thanks again!

**Comment by MoonKnight171** [comment]
I tried it and it works! I really appreciate your quick response and help—it made a big difference. I’d love to see more projects from you in the future. Thanks again!

**Comment by Den41k92** [comment]
Nice to hear that. You're welcome! I'm glad this small test program I wrote for myself 3 years ago turned out to be useful for someone else :)
